codeready-toolchain/api

pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go, pkg/apis/toolchain/v1alpha1/useraccount_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
We need **UserID** to create **Identity** and **UserIdentityMapping** resources.
=> Add UserID to MasterUserRecord and UserAccount

pkg/apis/toolchain/v1alpha1/useraccount_types.go
Two status constant added for UserAccount.  "provisioning" and "provisioned".
This will be used by member-operator/UserAccCtrl in PR https://github.com/codeready-toolchain/member-operator/pull/20
=> add useracc status const

pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
We are supposed to use this field only as a marker to initiate the status sync between MasterUserRecord and the corresponding UserAccount.
We still can use ResourceVersion as actual value when updating this field but we don't really care what value we set. Also it may happen that because of multiple concurrent reconciles the field will point to some outdated UserAccount resource version. Which is totally fine. So, to avoid potential confusion with the name let's rename it to `SyncIndex`.
=> Rename ResourceVersion to SyncIndex in MasterUserRecord

pkg/apis/toolchain/v1alpha1/conditions.go, pkg/apis/toolchain/v1alpha1/useraccount_types.go
I'm removing some conditions for **UserAccount** in https://github.com/codeready-toolchain/member-operator/pull/30
If that PR merged we need to cleanup the conditions in API (remove unused ones).
Also it introduces a **CondtionReady** type which can be used in other resources too.
=> Cleanup UserAccountConditions

pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go, pkg/apis/toolchain/v1alpha1/useraccount_types.go, pkg/apis/toolchain/v1alpha1/usersignup_types.go
use 'kubebuilder' build flags to specify extra
fields in the generated CRDs, namely for:
- short names
- additional printer columns
=> Preserve custom fields in crds

pkg/apis/toolchain/v1alpha1/useraccount_types.go, pkg/apis/toolchain/v1alpha1/usersignup_types.go
in the generated yaml files, the 'JSONPath' field would
contain backslashes before the quotes, which would cause
errors and prevent the field from being displayed in the
`oc get ...` commands
=> fix printcolumns tags

pkg/apis/toolchain/v1alpha1/usersignup_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Upstream issue:  https://jira.coreos.com/browse/CRT-225
This PR adds a username field to the `UserSignup` specification.  The username field will contain the original, unaltered username for the user signing up, while the `UserSignup`'s resource name will be set to a transformed version of this username in the case that it contains invalid characters.
=> Added username field to UserSignup spec

.codecov.yaml, README.adoc, make/go.mk, make/out.mk, make/test.mk
* moves test target from `go.mk` to `test.mk`
* adds a new target to run tests with coverage
* adds configuration for codecov
=> chore: add code coverage for tests

make/generate.mk
when CRDs are moved after generation, we need to add `_crd` suffix to the file name because it's required by operator-sdk csv generator
see https://github.com/operator-framework/operator-sdk/issues/1980
**Yes**
2. Does `make generate` change anything in other projects (host-operator, member-operator)? **[yes/no]**
**Yes** - just renames the files
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/71
- member-operator: https://github.com/codeready-toolchain/member-operator/pull/69
=> chore: add crd suffix to CRD file names-it's expected by operator-sdk csv generator

pkg/apis/toolchain/v1alpha1/nstemplatetier_types.go
This PR adds a short name 'tier' for NSTemplateTier CRD. So we can do `oc get tier`.
Yes.
Yes. See https://github.com/codeready-toolchain/host-operator/pull/79
=> Short name 'tier' for NSTemplateTier CRD

make/generate.mk, scripts/olm-catalog.sh
It modifies the script as well as the target so it creates CSV and hack files for member-operator repo
**yes**
**yes**
- member-operator: https://github.com/codeready-toolchain/member-operator/pull/77
=> feat(CRT-228): modify script so it creates CSV and hack files for member-operator

.golangci.yml
Configure the `timeout` value to 10min in `.golangci.yml`
1. Have you run `make generate` target? **no**
2. Does `make generate` change anything in other projects (host-operator, member-operator)? **no** 
fixes CRT-298
=> configure golangci-lint new timeout

README.adoc, scripts/olm-catalog.sh
we cannot have package and repository with the same name in quay and because the images are already pushed to `member-operator` and `host-operator` repositories, we need to rename the operators to be able to push the bundles to `toolchain-member-operator` and `toolchain-host-operator` packages
**yes**
**yes**
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/95 …
=> chore(CRT-331): rename operators to toolchain-host-operator and toolchain-member-operator

openshift-ci/Dockerfile.tools
Use correct key `78086003` when verifying operator-sdk 0.11.0 binary
**yes**
**no**
=> fix: use correct key when verifying operator-sdk binary

scripts/olm-catalog.sh
Drop  0.0.0 csv templates thanks to operator-sdk 0.11.0 as the generation of CSV works properly
**yes**
**yes**
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/97
- member-operator: https://github.com/codeready-toolchain/member-operator/pull/88
=> chore: drop 0.0.0 csv template thanks to operator-sdk 0.11.0

.github/pull_request_template.md, go.mod, go.sum, make/generate.mk, tools.go
Generate a KubeFedCluster CRD as an asset for toolchain-common
1. Have you run `make generate` target?
**yes**
2. Does `make generate` change anything in other projects (host-operator, member-operator)? **(NOTE: You can ignore it if the only changes are in the annotation `alm-examples` of the `ClusterServiceVersion` object)
**yes**
- toolchain-common: https://github.com/codeready-toolchain/toolchain-common/pull/52
=> Generate KubeFedCluster CRD

scripts/olm-setup.sh, scripts/push-to-quay-nightly.sh
This PR contains changes in olm scripts that includes:
* refactoring
* fixes in replacement logic of replace clause
* fix of using git - to use correct project dir
* changes in the order of calling the `setup-olm.sh` logic from `push-to-quay-nightly.sh`  as well as changes in the params that are passed
* using backup of operator package dir to not introduce any changes when `push-to-quay-nightly.sh` scripts is used
**yes**
**not in the CRDs but there is introduced .travis.yaml file in both …
=> fix(olm scripts): fix replace,git command and params for nightly

scripts/olm-catalog-generate.sh, scripts/olm-setup.sh, scripts/push-to-quay-nightly.sh
* Fix for the grep that was looking for "replace" clause - shouldn't fail when doesn't find replace clause 
* Improve help text by adding additional explanation and examples
**yes**
**no**
=> fix: grep shouldn't fail when doesn't find replace clause & improve help

openshift-ci/Dockerfile.tools
The builds are unreliable as it still uses the old Go 1.12
**yes**
**no**
=> chore: update tools in Dockerfile.tools

openshift-ci/Dockerfile.tools
add missing git community source
**yes**
**no**
verified (locally) that the git is really installed:
```
$ docker run -it tools
[root@aab285c96a62 api]# git version
git version 2.16.5
[root@aab285c96a62 api]# go version
go version go1.13.4 linux/amd64
```
=> fix: add missing git community source

openshift-ci/Dockerfile.tools
Add `jq` to the tools installed in the Docker image used on OpenShift CI
1. Have you run `make generate` target? **no**
=> add jq to CI tools

make/generate.mk
Add a target that copies the deployment template from registration-service repo to host-operator repo - for more information see:
https://github.com/codeready-toolchain/registration-service/pull/75
https://github.com/codeready-toolchain/host-operator/pull/111
**yes**
**yes**
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/111
=> feat(CRT-361): add target copying reg-service deployment to host repo

pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
Remove deprecated TargetCluster from MUR status
yes
yes
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/112
=> Remove deprecated TargetCluster from MUR status

scripts/push-to-quay-nightly.sh
use commit- prefix in the pre-release part to avoid cases when the pre-release version could contain leading zeroes - it's forbidden
**yes**
**no**
=> fix: use commit- prefix in the pre-release part

pkg/apis/toolchain/v1alpha1/usersignup_types.go
As an admin, I want to see the user email when approving an account. This makes my work easier as I can see where the user is coming from (e.g. redhat.com).
**Yes**
**Yes**
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/115
Relates to: 
jira - https://jira.coreos.com/browse/CRT-374
e2e- codeready-toolchain/toolchain-e2e#55
reg - codeready-toolchain/registration-service#78
=> Adding usersignup email

scripts/olm-setup.sh, scripts/push-to-quay-nightly.sh
rename IMAGE var to IMAGE_IN_CSV to avoid mismatch - the reason is that in toolchain-operator repo, there is the `IMAGE` variable defined in one makefile, so it replaced the values when it wasn't needed
**yes**
**no**
=> fix: rename IMAGE var to IMAGE_IN_CSV to avoid mismatch

pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Add Banned property to MasterUserRecord spec.
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/118
- member-operator: https://github.com/codeready-toolchain/member-operator/pull/104
=> CRT-373 add Banned property to MasterUserRecord

pkg/apis/toolchain/v1alpha1/usersignup_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
This PR adds a new `Deactivated` property to `UserSignup`, which may be used by an Admin to deactivate a user.
https://jira.coreos.com/browse/CRT-386
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/121
=> Add Deactivated property to UserSignup

pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
Add Che URL to MUR status
yes
yes
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/122
=> Add Che URL to MUR status

scripts/create-release-bundle.sh, scripts/olm-setup.sh, scripts/push-to-quay-nightly.sh
Add script `create-release-bundle.sh` that generates a final manifest files (operator bundle) in project-root/manifests directory
it also slightly refactors the current `push-to-quay-nightly.sh` and `olm-setup.sh` to reuse some code and to share the logic
**yes**
**no**
=> feat: add scripts for generating manifests

scripts/create-release-bundle.sh, scripts/olm-setup.sh
There was a wrong usage of the replace clause when the same release manifest was regenerated. Now it replaces the last manifest, but if the version is the same as the one that is being generated then it replaces the last but one.
**yes**
**no**
=> fix: don't add replace clause for the same version

scripts/create-release-bundle.sh, scripts/olm-setup.sh, scripts/push-to-quay-manifests.sh, scripts/push-to-quay-nightly.sh
This PR:
* add script `push-to-quay-manifests.sh` for pushing the latest manifest to quay.io for testing purposes. Consider the flow when we generate the relase manifest and we need to verify that it is working, so we use this script to push it to quay and then verify it in OpenShift
* I'll create useful makefile targets later
* when the `create-release-bundle.sh` is used, then it takes the latest commit sha from the origin/master. With the previous version it was hard to regenerate it with multiple commits created in a separated branch - it took the sha from HEAD of the branch, but we need the latest commit in master.
**yes**
2. Does `make generate` change anything in other projects (host-operator, member-operator, toolchain-common)? …
=> feat: add script for pushing manifests to quay

scripts/olm-setup.sh
don't remove empty lines from CSV, otherwise, it's not possible to create formated description like this one: https://github.com/codeready-toolchain/toolchain-operator/commit/9782d827cf0c26e1941fce84919eba652bbd3273
**yes**
**no**
=> fix(scripts): don't remove empty lines from CSV

go.mod, go.sum
update openshift/api to use release-4.2
**yes**
**yes**
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/131
- member-operator: https://github.com/codeready-toolchain/member-operator/pull/114
- toolchain-operator: https://github.com/codeready-toolchain/toolchain-operator/pull/49
=> chore: update openshift/api to release-4.2

pkg/apis/apis.go
The scheme should contain only CRs apis - this will get rid of the last `reflector.go:95: Failed to list`  errors from our logs
**yes**
(NOTE: You can ignore it if the only changes are in the annotation `olm-examples` of the `ClusterServiceVersion` object)
**no but it requires additional changes**
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/132
- member-operator: https://github.com/codeready-toolchain/member-operator/pull/115
=> chore: api scheme should contain only CRs

pkg/apis/toolchain/v1alpha1/useraccount_types.go
Renaming reason consts for user account to contain UserAccount prefix.
yes
no
=> renaming reason consts to add prefix UserAccount

scripts/enrich-by-envs-from-yaml.sh, scripts/olm-setup.sh, tools.go
Add script for enriching CSV by envs from config yaml file. The script adds fields that will set up environment variables for a deployment. The variables are taken from config yaml file specified as the source.
Example:
`./scripts/enrich-by-envs-from-yaml.sh ./path/to/csv.yaml ./path/to/e2e-test.yaml`
- Where `e2e-test.yaml` contain:
```
registration-service:
environment: 'e2e-tests'
auth-client:
library-url: 'https://sso.prod-preview.openshift.io/auth/js/keycloak.js'
```
then the script will append after the first occurrence of `env:` inside of `csv.yaml` file:
```
- name: REGISTRATION_SERVICE_AUTH_CLIENT_LIBRARY_URL
value: https://sso.redhat.com/auth/js/keycloak.js
- name: REGISTRATION_SERVICE_ENVIRONMENT
value: prod'
```
This will make the modification of variables in the registration …
=> feat(CRT-363): add script for enriching CSV by envs from config yaml file

scripts/create-release-bundle.sh, scripts/olm-catalog-generate.sh, scripts/olm-setup.sh, scripts/push-to-quay-manifests.sh, scripts/push-to-quay-nightly.sh
When the scripts are being fetched from GH location, in one case there was used a wrong path and in order to avoid such cases I replaced the last path of all other paths by a variables too.
**yes**
**no**
=> fix: use correct paths when fetching scripts from GH

scripts/olm-setup.sh
There are blocked OLM upgrades of host-operator - the reason is that OS didn't properly fetch some of the CSV versions and then it wasn't able to build the whole path of all replacements. In order to avoid it in the future, we will add `olm.skipRange` annotation so OLM will skip the versions that were not fetched.
**yes**
**no**
=> chore: add olm.skipRange for nightly releases

scripts/olm-setup.sh
Use digest instead of tag for defining docker images while generating CSV. The reason is the air-gapped installation of operators. see: https://docs.openshift.com/container-platform/4.2/operators/olm-restricted-networks.html
**yes**
**no**
=> chore(CRT-427): use digest instead of tag for defining docker images

pkg/apis/toolchain/v1alpha1/useraccount_types.go
Adding terminating reason. https://github.com/codeready-toolchain/member-operator/pull/105#discussion_r372159565
yes
no
=> adding terminating reason

pkg/apis/toolchain/v1alpha1/usersignup_types.go
Introduce a new email hash constant for UserSignup instead of using the BannedUser constant.
1. Have you run `make generate` target? **[n/a]**
This PR simply introduces a new constant, `UserSignupUserEmailHashAnnotationKey` and makes no structural changes to any CRD.
=> CRT-396 add a label key for UserSignup email hash value

scripts/enrich-by-envs-from-yaml.sh
check the availability of `yq` when it's needed to avoid: https://github.com/codeready-toolchain/toolchain-operator/pull/53
**yes**
**no**
=> fix: check the availability of yq when it's needed

pkg/apis/toolchain/v1alpha1/usersignup_types.go
This PR updates the constant name `UserSignupUserEmailHashAnnotationKey` to the more correct `UserSignupUserEmailHashLabelKey`.  (The value is a label, not an annotation).
This PR has no structural changes, and simply renames a constant.
=> Fix the naming of constant UserSignupUserEmailHashLabelKey

scripts/create-release-bundle.sh, scripts/olm-setup.sh, scripts/push-to-quay-manifests.sh, scripts/push-to-quay-nightly.sh
Adds parameter `--quay-namespace` - if not used then either content of `QUAY_NAMESPACE` env variable or the default value `codeready-toolchain` is used 
This is preparation for running CD builds via OpenShift Pipelines
**yes**
**no**
=> feat: add possibility to specify quay namespace via parameter

pkg/apis/toolchain/v1alpha1/nstemplatetier_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
Required by https://github.com/codeready-toolchain/host-operator/pull/157
yes
no
=> Make cluster resources a pointer so it's easy to use it as optional field

pkg/apis/toolchain/v1alpha1/usersignup_types.go
Move additional reason constants into api from host operator.  This change simply introduces new constant values, and doesn't change the structure of any resource definitions.
=> Moved constants from host operator

pkg/apis/toolchain/v1alpha1/nstemplateset_types.go
Adding a new constant for the status/reason when the cluster resources provisioning failed on the member lcluster
1. Have you run `make generate` target? **no**
Updates https://issues.redhat.com/browse/CRT-459
=> add reason for cluster resource provisioning error

README.adoc, openshift-ci/Dockerfile.tools
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/173
- member-operator: https://github.com/codeready-toolchain/member-operator/pull/140
~~When we merge this PR we will need to update the gpg key ID in Docker.tools file.~~
=> Update operator-sdk to 0.16.0

pkg/apis/toolchain/v1alpha1/nstemplateset_types.go
Adding the provider label key in order to add the provider label key to labels in the nstemplateset_controller. They will be removed from basic, advanced and teams (https://github.com/codeready-toolchain/host-operator/blob/master/deploy/templates/nstemplatetiers/.... ) 
Jira story: https://issues.redhat.com/browse/CRT-495
yes
no
=> adding provider label

pkg/apis/toolchain/v1alpha1/nstemplateset_types.go
reason to use when the NSTemplateSet termination failed
Updates https://issues.redhat.com/browse/CRT-459
2. Does `make generate` change anything in other projects (host-operator, member-operator, toolchain-common)? **no**
=> add reason for NSTemplateSet terminating error

pkg/apis/toolchain/v1alpha1/usersignup_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
In order to customize notification messages to users, we require additional user information which we should store in the UserSignup CRD when the user first registers. The fields we plan to extract and store for the purpose of the notification service messages include the user's first name, last name and company. 
Jira Task: https://issues.redhat.com/browse/CRT-518
yes
yes
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/182
=> adding fields for notification service

pkg/apis/toolchain/v1alpha1/tiertemplate_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
This field will be helpful to determine to which
specific tier this template is associated to.
This avoids having to parse the resource name.
2. Does `make generate` change anything in other projects (host-operator, member-operator, toolchain-common)? **yes** 
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/191
Updates https://issues.redhat.com/browse/CRT-500
=> feat: add TierTemplateSpec.TierName field

pkg/apis/toolchain/v1alpha1/tiertemplate_types.go
Add missing init func to register the new `TierTemplate` and `TierTemplateList` types in the toolchain/v1alpha1 scheme
2. Does `make generate` change anything in other projects (host-operator, member-operator, toolchain-common)? **no** 
Updates https://issues.redhat.com/browse/CRT-500
=> feat: register TierTemplate and TierTemplateList types

pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
Adds tier name to MUR printcolumns - it's very useful for managing MUR promotions
**yes**
**yes**
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/193
=> chore: add tier name to MUR printcolumns

pkg/apis/toolchain/v1alpha1/nstemplateset_types.go
Since we are moving to the `templateRef` field this PR is making it mandatory and the other fields (type, revision) optional.
In addition, there is a new label `/templateref` introduced and the old ones `/tier` and `/revision` removed, since they were just duplication of the information contained in the `/templateref` and there was no usage of it
**yes**
**yes** …
=> feat(CRT-501): make legacy fields optional and new ones mandatory

make/generate.mk
We have deleted notificationtemplate CRD but it's still in `make generate`. This PR cleans it up.
=> Delete notificationtemplate from CRD generation

pkg/apis/toolchain/v1alpha1/tiertemplate_types.go
Move constant containing type name of a template that contains cluster-scoped resources into api repo. In addition, I made the string lower case since the name of the resource shouldn't contain any capital letter anyway.
related PRs:
https://github.com/codeready-toolchain/host-operator/pull/210
https://github.com/codeready-toolchain/member-operator/pull/160
=> chore: move constant containing clusterresources type name to api

README.adoc, make/generate.mk
This PR handles 2 things:
1. Add a note to ensure users are aware that the toolchain repositories should be checked out under your GOPATH in order for the api generation to work correctly.
2. Trying to add CRDs with names that end with a 's' character results in the generate target failing with the following error:
```
go mod vendor
re-generating the deepcopy go file...
go run /Users/rajiv/go/src/github.com/codeready-toolchain/api/vendor/k8s.io/code-generator/cmd/deepcopy-gen/main.go \
--input-dirs ./pkg/apis/toolchain/v1alpha1/ -O zz_generated.deepcopy \
--bounding-dirs github.com/codeready-toolchain/api/pkg/apis "toolchain:v1alpha1" \
--go-header-file=make/go-header.txt
re-generating the openapi go file...
go run /Users/rajiv/go/src/github.com/codeready-toolchain/api/vendor/k8s.io/kube-o …
```
=> Handle CRD names ending with s and add a note about api generation

README.adoc, make/generate.mk, scripts/generate-deploy-hack.sh, scripts/olm-setup.sh
The changes in this PR brings support of operator-sdk to our scripts. With these changes, we can use both versions of operator-sdk 0.16.0 and 0.17.1
This is very first step of supporting operator-sdk 0.17.1. After this, we will
1. migrate all repositories to use operator-sdk 0.17.1 in their dockerfiles
2. drop support of operator-sdk 0.16.0 in our scripts
3. adapt the structure of the repositories and the logic of our scripts to properly use operator-sdk 0.17.1
4. ... and some more steps that are still not clear right now :-) ...
=> feat: support both versions of operator-sdk 0.16.0 and 0.17.1

pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go, pkg/apis/toolchain/v1alpha1/nstemplateset_types.go, pkg/apis/toolchain/v1alpha1/nstemplatetier_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
I changed the `listType` to `atomic` because:
* in MUR for `status.UserAccounts` because there is no field that would be used as a map key - the cluster is of the object type which cannot be used as a key.
* in both NSTemplateTier and NSTemplateSet because it makes more sense to have them as atomic since it more or less contains only the `templateRef` field
**yes**
**yes** …
=> fix: use correct listType=atomic when needed or it makes sense

README.adoc, scripts/olm-setup.sh
Drops the support of operator-sdk 0.16.x and supports only 0.17.x
=> chore: drop opeator-sdk 0.16.x support

scripts/create-release-bundle.sh, scripts/generate-cd-release-manifests.sh, scripts/olm-catalog-generate.sh, scripts/olm-setup.sh, scripts/push-manifests-as-app.sh, scripts/push-to-quay-manifest.sh, scripts/push-to-quay-nightly.sh, scripts/recover-operator-dir.sh
The main change in this PR is that the logic from the `push-to-quay-nightly.sh` script is split into multiple scripts so they can be called separately and with different parameters.
The new scripts are:
* `generate-cd-release-manifests.sh` - (re)generates the manifests files for the new release
* `push-manifests-as-app.sh` - creates the versioned directory and pushes the manifests into quay application
* `recover-operator-dir.sh` - recovers the operator bundle directory from the backup folder
Along with these changes I also modified a few more things:
* the channel is taken from the parameters so it's not hardcoded
* `setup_variables` function is read as part of the `read_arguments` so it doesn't have to be called separately
* moved `setup_version_variables_based_on_commits` function to …
=> chore: split push-to-quay-nightly.sh script into multiple scripts

scripts/create-release-bundle.sh, scripts/generate-deploy-hack.sh, scripts/olm-setup.sh, scripts/recover-operator-dir.sh
We will need to execute the particular steps of the release process in separated containers in the CD so we cannot use the `/tmp` directory for storing some intermediate files - in case we would need the file read in the next step. Thus, there is a new option allowing us to specify a temp directory location.
=> feat: add ability to specify temp directory location

pkg/apis/toolchain/v1alpha1/conditions.go, pkg/apis/toolchain/v1alpha1/memberstatus_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
Makes `LastUpdatedTime` truly optional. The api will be able to handle when the value is nil. Also added some status reason constants needed for MemberStatus.
yes
yes
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/232
- member-operator: https://github.com/codeready-toolchain/member-operator/pull/173
- toolchain-common: https://github.com/codeready-toolchain/toolchain-common/pull/114
=> Make LastUpdatedTime truly optional

scripts/create-release-bundle.sh
When the scripts generate a new release manifests (in the old bundle format), then it should not include the `bundle.Dockerfile` nor the `metadata/`
=> fix: delete bundle files when doing final releases

pkg/apis/toolchain/v1alpha1/notification_types.go
This PR just adds a couple of new reason constants.
Fixes https://issues.redhat.com/browse/CRT-678
**NotificationContextError** is set when there is an error while attempting to create a new notification context.
**NotificationDeliveryError** is set when there is an error during delivery of a notification.
*Not applicable - this PR only adds new constants*
=> Add required reason constants for Notification Controller

pkg/apis/toolchain/v1alpha1/nstemplatetier_types.go, pkg/apis/toolchain/v1alpha1/templateupdaterequest_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
add condition and reasons for the TemplateUpdateRequest
also, in TemplateUpdateRequest.Status, add a `SyncIndexes` field which
will contain the `MasterUserRecord.UserAccount[].SyncIndex` as they existed
when the MasterUserRecord template refs were updated.
The TemplateUpdateRequest controller will track the changes on the `MasterUserRecord`
until ALL sync indexes in the status changed, at which point, the MasterUserRecord update
will be considered as complete.
2. Does `make generate` change anything in other projects (host-operator, member-operator, toolchain-common)? **yes** 
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/230
- toolchain-common: …
=> add condition and SyncIndexes in TemplateUpdateRequest status

scripts/push-bundle-and-index-image.sh
This PR adds an additional function to the bash script that generates and pushes a bundle image and an index image to quay.
This new function is trying to solve conflicts that we can sometimes see when a host-operator PR is merged at the same time as registration-service PR. If it happened, then the build would fail because of a missing version in the index image.
The new function is trying to get the latest bundle image version form the index image. Then it validates if there is a possibility that such a conflict could happen and if so, then it checks if it can use the latest version from the index image.
More info in the inline comments in the code
=> fix: try to check and use the latest bundle image version in index

pkg/apis/toolchain/v1alpha1/templateupdaterequest_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Change the list type of `TemplateUpdateRequest.Status.Conditions` to `atomic` so there is no merging of the entries. This will allow for duplicate entries in the conditions, when multiple failures happened when trying to update a `MasterUserRecord`
2. Does `make generate` change anything in other projects (host-operator, member-operator, toolchain-common)? **yes** 
- https://github.com/codeready-toolchain/host-operator/pull/243
=> convert TemplateUpdateRequest status conditions to atomic list

pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Adds the new MUR.Status.ProvisionedTime field that will be used to track when a user is first successfully provisioned. It will be the start time used for automatic user deactivation.
Related Issue:
https://issues.redhat.com/browse/CRT-754
yes
host-operator
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/261
- toolchain-common: https://github.com/codeready-toolchain/toolchain-common/pull/122
=> Add ProvisionedTime to MUR status

pkg/apis/toolchain/v1alpha1/usersignup_types.go
This PR simply adds a new reason constant:
`UserSignupVerificationRequiredReason           = "VerificationRequired"`
2. Does `make generate` change anything in other projects (host-operator, member-operator, toolchain-common)? **[n/a]** 
- host-operator: n/a
- member-operator: n/a
- toolchain-common: n/a
=> Added VerificationRequired reason constant

pkg/apis/toolchain/v1alpha1/usersignup_types.go
This PR fixes a simple typo in the `UserVerificationExpiryAnnotationKey` constant name.
1. Have you run `make generate` target? **[n/a]**
=> Fixed typo in constant name

pkg/apis/toolchain/v1alpha1/usersignup_types.go
We need to set `approved` label with values `true` or `false` at the `UserSignup` resource to easily filter the unapproved ones.
In order to achieve that I'm adding the label key, its values, and a condition reason that will be used for the case when a change of the label fails.
=> chore: add approved label key to UserSignup type

scripts/generate-cd-release-manifests.sh, scripts/olm-setup.sh, scripts/push-bundle-and-index-image.sh
This PR introduces two new params and functionalities into the CD scripts:
* `--index-per-commit` - when set to true, then the CD script will generate & push a new index image per release/commit. That means that it won't use the `latest` tag but will generate a new one for every release - the tag will equal to the tag of the bundle image.
* `--first-relase` - when set to true, then the generation scripts will generate CSV without any replacement. That means that the release is supposed to be the first one. The bundle&index push script detects that there is no replacement and if the `--index-per-commit` is used as well, then it doesn't use the `--from-index` param when adding a new bundle to the index image.
=> feat(script): introduce first release param and index per commit

pkg/apis/toolchain/v1alpha1/usersignup_types.go
Just adds some constants that will be used for the user deactivation status on UserSignup resources. It allows us to keep track of whether a notification regarding the deactivation was sent to the user already so that we prevent sending repeat emails.
Related PR: https://github.com/codeready-toolchain/host-operator/pull/289
yes
no
n/a
=> Add constants for deactivation notification conditions

pkg/apis/toolchain/v1alpha1/usersignup_types.go
Adds UserSignup `state` label as a replacement of the `approved` one
yes
yes
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/297
=> feat: add UserSignup state label

pkg/apis/toolchain/v1alpha1/toolchaincluster_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Drop zones and region from ToolchainCluster CR because:
* it doesn't bring any additional value
* requires additional cluster-scoped permission to access `Nodes`
* makes the stuff a bit simpler
* if we are interested in Node zones & region, we should put it into Member/ToolchainStatus CRs
yes
yes
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/303 …
=> chore: drop zones and region from ToolchainCluster

pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
This minor PR introduces a new condition constant only, in support of https://issues.redhat.com/browse/CRT-829
Adds a new `ToolchainStatusUnreadyNotificationCreated` condition, used when a notification is sent to an admin mailing list to indicate the toolchain has been in an unready status for an extended period of time.
=> Add toolchain status unready notification condition

pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
Oops, I need an additional reason constant for https://issues.redhat.com/browse/CRT-829
Additional constant required for above issue.  No structural changes made.
=> Unready Notification Sent Reason added for toolchain status operator

pkg/apis/toolchain/v1alpha1/notification_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Fix for https://issues.redhat.com/browse/CRT-829
This PR adds a new `recipient` property to the Notification CRD spec.
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/313
=> Added recipient to notification CRD spec

pkg/apis/toolchain/v1alpha1/notification_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Adds subject and notification optional properties to the Notification CRD.
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/317
=> CRT-829 added subject and content properties to notification

pkg/apis/toolchain/v1alpha1/useraccount_types.go
Adds a condition type for the Che deletion condition used by the useraccount controller. This condition is used to store the Che user ID in the status until deletion completes. The deletion API requires the user ID as a parameter and will return an error until the user is successfully removed. In some cases the user could be reported as non-existent while the deletion is still in progress so the user ID will not be retrievable from the user API but the cached user ID can be used with the Che user deletion API on retries.
2. Does `make generate` change anything in other projects (host-operator, member-operator, toolchain-common)? **no**  …
=> Che delete condition

pkg/apis/toolchain/v1alpha1/useraccount_types.go
Removes the UserAccountCheCleanup  and UserAccountDeletingCheDataReason constants since they'll be removed by https://github.com/codeready-toolchain/member-operator/pull/228
yes
no
None
=> Removes unused che condition type and reason

pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go, pkg/apis/toolchain/v1alpha1/usersignup_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Fix for https://issues.redhat.com/browse/CRT-915
Adds a UserID property to UserSignup specification.  Adds a new label constant for `owner` label in MasterUserRecord.
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/359
=> Added UserID property to UserSignup specification

pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
This PR is part of the cleanup step for https://issues.redhat.com/browse/CRT-915
This PR removes the deprecated `user-id` label constant.  Constant removal only, no structural changes made to resources
=> Remove deprecated user-id label constant

pkg/apis/toolchain/v1alpha1/notification_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Signed-off-by: sbryzak <sbryzak@gmail.com>
This PR renames the `Delivered` printcolumn to `Sent` in the Notification CRD.
Fixes https://issues.redhat.com/browse/CRT-983
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/386
=> CRT-983 renamed Delivered display column to Sent

scripts/push-bundle-and-index-image.sh
in GH action it's not needed since it always uses the latest one
=> fix: use binary image param only for local execution

pkg/apis/toolchain/v1alpha1/notification_types.go, pkg/apis/toolchain/v1alpha1/usersignup_types.go
This PR adds constants for a new "deactivating" UserSignup condition in order to manage the notifications sent to users prior to them becoming deactivated.  Only constants have been added, no structural changes to CRDs.
Fixes https://issues.redhat.com/browse/CRT-994
=> Added new constants for user pre-deactivation notification

pkg/apis/toolchain/v1alpha1/memberstatus_types.go, pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
as per the conversation in https://github.com/codeready-toolchain/host-operator/pull/394, moving apiEndpoint from MemberStatus to Member wrt: https://issues.redhat.com/browse/CRT-971 
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/395
- member-operator: https://github.com/codeready-toolchain/member-operator/pull/240
=> moving ApiEndpoint from MemberStatus to Member

pkg/apis/toolchain/v1alpha1/usersignup_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
This PR introduces a new string property type called `UserSignupState`, used to enforce the type of values set for the `states` property.
=> Enforce states property type

pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
Added a Condition Reason of ToolchainStatus for RestoredNotificationCR creation fail
=> added restored notifcation condition reason

pkg/apis/toolchain/v1alpha1/usersignup_types.go
This PR modifies the existing "UserIsActive" reason to a more precise "UserNotInPreDeactivation" description.  Constant value changed only, no structural changes made.
2. Does `make generate` change anything in other projects (host-operator, member-operator, toolchain-common)? **[N/A]** 
=> Modify reason constant for user in pre-deactivation phase

pkg/apis/toolchain/v1alpha1/usersignup_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
This PR removes the Deactivated property from UserSignup.Spec.  
Fixes https://issues.redhat.com/browse/CRT-1087
Replaces the `Deactivated` printcolumn with a generic `States` column that prints all states, e.g (scroll right):
```
NAME                                   USERNAME               FIRST NAME   LAST NAME   COMPANY   TARGETCLUSTER   COMPLETE   REASON   APPROVED   APPROVEDBY   STATES                       COMPLIANTUSERNAME   EMAIL
1a03ecac-7c0b-44fc-b66d-12dd7fb21c40   johnsmith@redhat.com                                      east-2a                                                                                                      johnsmith@redhat.com
1a03ecac-7c0b-44fc-b66d-12dd7fb21c41   johnsmith@redhat.com                                      east-2a …
```
=> Removed Deactivated property from Spec

pkg/apis/toolchain/v1alpha1/usersignup_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
This PR removes the `UserSignup.Spec.VerificationRequired` property
Fixes https://issues.redhat.com/browse/CRT-1103
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/423
=> Removed VerificationRequired property

pkg/apis/toolchain/v1alpha1/usersignup_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Renames `UserID` to Userid`
adds missing listType to states
**yes**
**yes**
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/436
=> fix: rename UserID->Userid & add missing listType

api/v1alpha1/usersignup_types.go, api/v1alpha1/zz_generated.openapi.go
This PR removes the UserSignup.Spec.Approved property, which has been replaced by UserSignup.Spec.States
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/446
=> Removed UserSignup.Spec.Approved property

.gitignore, go.sum, make/clean.mk, make/generate.mk, make/get-tool.mk, make/go.mk
I decided to drop vendoring in order to get the needed version of the "generate" tools and start using a smarter version of what is generated by operator-sdk. It gets the binaries via `go get` command and stores them in `/bin` directory together with a file that contains the used versions of the binaries - to make sure that the correct version is used.
The main reason for doing it is that we will need the `kubebuilder` binary also in host/member operator repositories and keeping the vendor folder is sometimes pretty annoying. So, the same approach will be used in host/member operator repos to get `kubebuilder` & `kustomize` binaries.
I know that we agreed on not installing binaries from repos in makefiles targets, but - to be honest - I don't see any difference between getting the …
=> chore: drop vendoring and get tools with go

api/v1alpha1/notification_types.go
Add missing `omitempty` json marker as the `Context` field is optional
yes
No
=> fix: add missing omitempty json marker

scripts/install-operator.sh
use 100s as deployment limit so we don't have to wait 300s
the rest of the changes `; \` is leftover from makefile target
=> fix: use 100s as deployment limit

api/v1alpha1/masteruserrecord_types.go, api/v1alpha1/useraccount_types.go, api/v1alpha1/usersignup_types.go, api/v1alpha1/zz_generated.openapi.go
This PR adds a new optional property `OriginalSub` to the following CRD resources:
- UserSignup
- MasterUserRecord
- UserAccount
This will be a temporary property used for the purposes of migrating users to a new IdP client.
Fixes https://issues.redhat.com/browse/CRT-1254
Host Operator PR: https://github.com/codeready-toolchain/host-operator/pull/518
Member Operator PR: https://github.com/codeready-toolchain/member-operator/pull/300
=> Added OriginalSub property to UserSignup, MUR and UserAccount CRDs

api/v1alpha1/usersignup_types.go
Adds an annotation that will be used to track the last target cluster for a UserSignup. It will be used to ensure returning users can be provisioned to the same target cluster they were previously provisioned to.
yes
no
n/a
=> Add an annotation to track the last target cluster

api/v1alpha1/usersignup_types.go
Add a UserSignupUnableToUpdateAnnotationReason 
yes
no
n/a
=> Status condition reason for last cluster annotation

api/v1alpha1/toolchainevent_types.go, api/v1alpha1/zz_generated.openapi.go
This PR removes the `ActivationCode` property from `ToolchainEvent.Spec`, and instead introduces a new label constant so that the activation code can instead be stored as a label value.  This will enable easier lookup of the `ToolchainEvent` resource.
2. Does `make generate` change anything in other projects (host-operator, member-operator)? **[yes]**
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/538
=> Removed ActivationCode from Spec, added constant for activation-code label

api/v1alpha1/toolchainconfig_types.go, api/v1alpha1/zz_generated.deepcopy.go, api/v1alpha1/zz_generated.openapi.go
Adds a DefaultSpaceTier configuration field to Toolchainconfig.
Related Issue: https://issues.redhat.com/browse/CRT-1318
1. Have you run `make generate` target? **[yes/no]** yes
2. Does `make generate` change anything in other projects (host-operator, member-operator)? **[yes/no]** yes
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/#
=> Default space tier

api/v1alpha1/changetierrequest_types.go
See also https://github.com/codeready-toolchain/host-operator/pull/558
Not used anywhere else: https://github.com/search?q=org%3Acodeready-toolchain+ChangeTierRequestChangeFiledReason&type=code
=> chore: fix typo in const name

api/v1alpha1/space_types.go
New constants used in https://github.com/codeready-toolchain/host-operator/pull/562
=> feat: add const for space retargeting

api/v1alpha1/nstemplateset_types.go, api/v1alpha1/zz_generated.openapi.go
See also:
- https://github.com/codeready-toolchain/toolchain-common/pull/227
- https://github.com/codeready-toolchain/host-operator/pull/567
- https://github.com/codeready-toolchain/member-operator/pull/323
- https://github.com/codeready-toolchain/toolchain-e2e/pull/434
Fixes https://issues.redhat.com/browse/CRT-1382
=> refactor: remove support for custom templates in NSTemplateSet

api/v1alpha1/labels.go, api/v1alpha1/space_types.go, api/v1alpha1/usersignup_types.go, api/v1alpha1/zz_generated.openapi.go
This PR make two changes:
* makes the `Space.Spec.TierName` optional so it can be filled by the SpaceCompletionController as well
* adds Space state label key with two values:
* pending - when Space doesn't have assigned any cluster
* pending - when Space already have an assigned cluster
This will be used in two cases:
* capacity management
* metrics (counting how many Spaces are provisioned in which clusters)
I also introduced two generic contants for the `state` key and `pending` value because
* the values are the same as are used in `UserSignups` as well as in `Spaces`
* the capacity management will be generic to work with both types, so it will use this generic constant
1. Did you run `make generate` target? **[yes/no]**
yes
2. Did `make generate` change anything in other projects …
=> feat: introduce Space state label & make tierName optional

api/v1alpha1/usersignup_types.go
Adds the `toolchain.dev.openshift.com/skip-auto-create-space` annotation for usersignups that when true signals the usersignup controller to skip Space creation
=> Introduce auto-create-space usersignup annotation

api/v1alpha1/usersignup_types.go
Removes the `UnableToDeleteSpace` UserSignup reason because the space deletion will be handled by the Space cleanup controller. But the usersignup controller will need to create a SpaceBinding so the `UnableToCreateSpaceBinding` is added.
n/a - just a constants change
=> Add usersignup unable to create SpaceBinding reason

api/v1alpha1/tiertemplate_types.go
Adds an annotation to be used to mark a TierTemplate object as optional. That means that it won't be applied if the corresponding API group is not present in the cluster.
=> feat: add otional-resource annotation for TierTemplate objects

api/v1alpha1/masteruserrecord_types.go
It drops the SyncIndex from MUR. This is the last step of https://issues.redhat.com/browse/CRT-1306
1. Did you run `make generate` target? **[yes/no]**
**yes**
3. Did `make generate` change anything in other projects (host-operator, member-operator)? **[yes/no]**
**yes**
5. In case of **new** CRD, did you also update make/generate.mk in this repository and `resources/setup/roles/host.yaml` in the sandbox-sre repository?
N/A
7. In case other projects are changed, please provides PR links.
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/620
related PRs:
* https://github.com/codeready-toolchain/toolchain-common/pull/246
* https://github.com/codeready-toolchain/host-operator/pull/620
* https://github.com/codeready-toolchain/member-operator/pull/353
* …
=> refactoring: drop syncIndex from MUR

api/v1alpha1/toolchainconfig_types.go, api/v1alpha1/zz_generated.deepcopy.go, api/v1alpha1/zz_generated.openapi.go
Adds a new config field for the "Default User Tier" since just "Default Tier" can be confused for either User or Space. `DefaultTier` will be removed in a following PR.
3. In case of **new** CRD, did you the following? **n/a** …
=> Default user tier

api/v1alpha1/usersignup_types.go
Just adds a `NoUserTierAvailable` reason for when a UserTier cannot be found during user signup.
=> Add NoUserTierAvailable const

api/v1alpha1/memberoperatorconfig_types.go, api/v1alpha1/zz_generated.deepcopy.go, api/v1alpha1/zz_generated.openapi.go
Adds `SkipUserCreation` to the MemberOperatorConfig to control whether User and Identity resources should be created. This will primarily be used for the appstudio staging cluster to prevent appstudio tier users from User and Identities conflicts.
3. In case of **new** CRD, did you the following? **n/a**
4. In …
=> Skip user creation config

api/v1alpha1/nstemplatetier_types.go, api/v1alpha1/zz_generated.openapi.go
Removes the `DeactivationTimeoutDays` field from the NSTemplateTier type. `DeactivationTimeoutDays` is now part of the `UserTier` type only.
Related Issue: https://issues.redhat.com/browse/ASC-49
3. In case of **new** CRD, did you the following? **n/a**
4. In case other projects are changed, please provides PR …
=> Remove deactivation timeout days

api/v1alpha1/usersignup_types.go
adding a condition type and condition reason to indicate usersignup provisioning is in progress.
4. In case other projects are changed, please provides PR links. - **NA**
=> Provisioning user signup

api/v1alpha1/space_types.go, api/v1alpha1/zz_generated.openapi.go
This PR adds `parentSpace` field to the `Space` CRD, covers the first acceptance criteria from https://issues.redhat.com/browse/ASC-247.
2. Did `make generate` change anything in other projects? **yes**
host-operator
N/A
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/723
=> add parentSpace field in Space CRD and minor comment fix

api/v1alpha1/workspace_types.go, api/v1alpha1/zz_generated.openapi.go
Adds "type" to Workspace CRD that can be used to identify a user's "home" workspace.
3. In case of **new** CRD, did you the following? **n/a**
- member-operator: https://github.com/codeready-toolchain/member-operator/pull/409
=> Add workspace type

api/v1alpha1/usersignup_types.go
Adds constants for new annotation values for the purpose of storing a couple of SSO token claims used for Pendo integration.  No structural changes in this PR, constants only.
1. Did you run `make generate` target? **no**  
2. Did `make generate` change anything in other projects (host-operator, member-operator)? **yes/no**  N/A
=> Added constants for user_id and account_id

api/v1alpha1/spacerequest_types.go
Add labels for linking Spaces to the SpaceRequest that provisioned them.
Jira: https://issues.redhat.com/browse/ASC-257
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/770
- e2e: https://github.com/codeready-toolchain/toolchain-e2e/pull/685
- toolchain-cicd: https://github.com/codeready-toolchain/toolchain-cicd/pull/88
=> Implement creation of sub-spaces in SpaceRequest controller

api/v1alpha1/space_types.go
Drop unused label `workspace` 
Part of Jira: https://issues.redhat.com/browse/SANDBOX-51 
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/824
=> fix: drop label WorkspaceLabelKey

api/v1alpha1/spacenamespaces.go
Just introduces a constant for default namespace since we should probably use a common value in the different codebases. Having the common constant ensures we don't rename it and accidentally break other areas of the code.
It should be used in the following places:
- in the member operator nstemplateset code that sets the default namespace in Space Status: https://github.com/codeready-toolchain/member-operator/blob/450b77ca311fc11daa9a328d5cc62115f11a4ff7/controllers/nstemplateset/status.go#L74
- in the reg svc endpoint that looks up the default namespace for a user: https://github.com/codeready-toolchain/registration-service/blob/b8f6dfcc8a1e1080aa7f5ef35b5f6de12f507e59/pkg/signup/service/signup_service.go#L541
I can make the changes in those places once this PR is merged.
=> Use constant for default namespace type

api/v1alpha1/usersignup_types.go, api/v1alpha1/zz_generated.openapi.go
This PR adds the user's email address to the propagated claims copied down from UserSignup to other resources
3. In case of **new** CRD, did you the following? **yes/no**
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/861 …
=> Propagate email claim to downstream resources

.github/workflows/ci-build.yml
As of [June 2023][1], GitHub no longer uses node v12 within its actions runner by default.  They have been encouraging action authors to switch to node v16 and [encouraging users][2] to use the new versions of the actions when they become available, with the intent on removing node v12 sometime in the near future.
Bump the versions of the affected actions to bring this in line.
[1]: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
[2]: https://github.com/codeready-toolchain/host-operator/actions/runs/6421632076
=> ci: bump actions to silence node12 warnings

api/v1alpha1/workspace_types.go, api/v1alpha1/zz_generated.openapi.go
Add missing open api markers
2. Did `make generate` change anything in other projects (member-operator)? **yes**
- member-operator: https://github.com/codeready-toolchain/member-operator/pull/482
=> fix: add missing open api marker to ws structs

api/v1alpha1/usersignup_types.go, api/v1alpha1/zz_generated.openapi.go
This field is going to be used by the proxy when no workspace context is provided.
Ref. Ref. https://issues.redhat.com/browse/SANDBOX-425
3. In case of **new** CRD, did you the following? **no** …
=> Add HomeSpace status field

api/v1alpha1/toolchainconfig_types.go, api/v1alpha1/zz_generated.deepcopy.go, api/v1alpha1/zz_generated.openapi.go
Add a new field for configuring the automatic verification threshold.
Jira: https://issues.redhat.com/browse/SANDBOX-495
2. Did `make generate` change anything in other projects (host-operator)? **yes**
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/942
=> add automatic verification threshold field

api/v1alpha1/usersignup_types.go
This PR updates the API to support refactoring the UserSignupController to only use IdentityClaims as the source of the user's token claim values.
No structural changes made, no breaking changes made (only new annotations added).
=> Added annotations for UserSignupController

api/v1alpha1/masteruserrecord_types.go
Take the target cluster the MUR is provisioned to from status
3. In case of **new** CRD, did you the following? **no**
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/952
=> print target cluster from status

api/v1alpha1/masteruserrecord_types.go, api/v1alpha1/useraccount_types.go, api/v1alpha1/usersignup_types.go, api/v1alpha1/zz_generated.openapi.go
This PR reverts the changes that made IdentityClaims / PropagatedClaims required.
3. In case of **new** CRD, did you the following? **yes/no**
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/961 …
=> Revert change to make propagated claims required

api/v1alpha1/usersignup_types.go, api/v1alpha1/zz_generated.openapi.go
Made the UserSignup.Spec.IdentityClaims property required instead of optional
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/973
=> Made IdentityClaims required

api/v1alpha1/toolchaincluster_types.go, api/v1alpha1/zz_generated.deepcopy.go, api/v1alpha1/zz_generated.openapi.go
This is related to https://github.com/codeready-toolchain/host-operator/pull/1017#issuecomment-2082716929 . Making the LastProbeTime optional first …
=> KUBESAW-43: Make LastProbeTime Optional

api/v1alpha1/auth.go
Signed-off-by: Francesco Ilario <filario@redhat.com>
JIRA: https://issues.redhat.com/browse/ASC-531
This PR adds a constant value for the `kubesaw-authenticated` special user.
3. In case of **new** CRD, did you the following? N/A
4. In case other projects are changed, please provides PR links. N/A
=> add kubesaw-authenticated username constant

api/v1alpha1/toolchaincluster_types.go
A trivial PR to add the definition of the new label required for the implementation of https://issues.redhat.com/browse/KUBESAW-16. 
Related PRs:
- toolchain-common: https://github.com/codeready-toolchain/toolchain-common/pull/396
- toolchain-cicd: https://github.com/codeready-toolchain/toolchain-cicd/pull/109
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/1030
- toolchain-e2e: https://github.com/codeready-toolchain/toolchain-e2e/pull/970
3. In case of **new** CRD, did you the following? **no, not a new CRD**
- …
=> Add the definition of the toolchain-cluster label to the API so that it can be reused freely throughout the codebase.

api/v1alpha1/spaceprovisionerconfig_types.go
This adds a new reason for SpaceProvisionerConfig not being ready. As such this is no API change.
Related PRs:
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/1033
- toolchain-e2e: https://github.com/codeready-toolchain/toolchain-e2e/pull/977
1. Did you run `make generate` target? **no, not needed**
=> Trivial Add a new SPC Ready reason.

api/v1alpha1/memberoperatorconfig_types.go, api/v1alpha1/zz_generated.openapi.go
Update the `WebhookConfig.Deploy` field which now is used in a different way. Based on the changes [in this PR](https://github.com/codeready-toolchain/member-operator/pull/562) and related ones, the webhook will still be deployed but deleted afterwords.
Those PRs will be merged only after the new behavior is merged to master. 
- `CSV` file: …
=> update webhook deploy comment

api/v1alpha1/usersignup_types.go
Adds a constant to be used as an annotation key in the UserSignup.
eg.
```
apiVersion: toolchain.dev.openshift.com/v1alpha1
kind: UserSignup
metadata:
annotations:
toolchain.dev.openshift.com/captcha-assessment-id: "asdf-qwerty"
...
```
1. Did you run `make generate` target? **yes/no** no, just added a constant
2. Did `make generate` change anything in other projects (host-operator, member-operator)? **N/A**
- `CSV` file: https://github.com/codeready-toolchain/host-operator/blob/master/config/manifests/bases/host-operator.clusterserviceversi …
=> Add recaptcha assessment id annotation

api/v1alpha1/usersignup_types.go
Adds a constant for the captcha annotated assessment to be used as an annotation key in the UserSignup.
https://issues.redhat.com/browse/SANDBOX-626
eg.
```
apiVersion: toolchain.dev.openshift.com/v1alpha1
kind: UserSignup
metadata:
annotations:
toolchain.dev.openshift.com/captcha-annotated-assessment: "FRAUDULENT"
...
```
The other possible value is `LEGITIMATE`
1. Did you run `make generate` target? **no**
3. In case of **new** CRD, did you the following? **no**
- `CSV` file: …
=> Add an annotation to UserSignup for captcha annotated assessment

README.adoc
In order to be align with the other repos, this PR adds the go reference card to the README.
It also deletes codecov card since I think is unnecessary in this repo context.
=> add go reference card and delete codecov card

api/v1alpha1/banneduser_types.go
add `BannedByLabelKey` to avoid duplication and mismatches across repos
4. In case other projects are changed, please provides PR links. **NA**
[SANDBOX-674](https://issues.redhat.com/browse/SANDBOX-674)
=> SANDBOX-674: add BannedByLabelKey

.github/workflows/ci-build.yml
uses go-version-file instead of go-version. One less place to change when making updates.
4. In case other projects are changed, please provides PR links. **N/A**
=> SANDBOX-677 use go-version-file

api/v1alpha1/docs/apiref.adoc, api/v1alpha1/memberoperatorconfig_types.go, api/v1alpha1/zz_generated.deepcopy.go, api/v1alpha1/zz_generated.openapi.go
This PR introduces an additional param to member configuration to manage CPU requests/limits in our Autoscaler buffer.
See https://issues.redhat.com/browse/SANDBOX-659 for more details.
Related PRs:
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/1070
- member-operator: https://github.com/codeready-toolchain/member-operator/pull/591
=> Add CPU to Autoscaler buffer

api/v1alpha1/docs/apiref.adoc, api/v1alpha1/socialevent_types.go, api/v1alpha1/zz_generated.openapi.go
Replaces `PreferSameCluster`, which is not currently used at all, by `TargetCluster`
Part of https://issues.redhat.com/browse/SANDBOX-724
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/1075
=> Add target cluster to social event

api/v1alpha1/banneduser_types.go, api/v1alpha1/docs/apiref.adoc, api/v1alpha1/zz_generated.openapi.go
To know why the user was banned, the `Reason` field should be added to `BannedUserSpec`.
1. Did you run `make generate` target? yes
2. Did `make generate` change anything in other projects (host-operator, member-operator)? yes
4. In case of **new** CRD, did you the following?  no
5. In case other projects are changed, please provides PR links.
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/1081 …
=> SANDBOX-681: add 'Reason' field to BannedUserSpec

make/generate.mk
let's drop the logic that syncs the registration-service.yaml file between host-operator and registration-service repos as it doesn't make any sense.
related PR https://github.com/codeready-toolchain/registration-service/pull/459
=> drop registration-service.yaml from registration-service repo

scripts/verify-replace.sh
Introduce a make command for pre-requisite of verify-replace script as host-operator and member operator require tiers and assets to be ready before any changes to go mod
Initially this was not required for the api repo, but now this same error started appearing while running from api repo too hence updating the script to be similar to toolchain common - https://github.com/codeready-toolchain/toolchain-common/pull/429 
1. Did you run `make generate` target? **NA**
2. Did `make generate` change anything in other projects (host-operator, member-operator)? **NA**
- `PROJECT` file: …
=> KUBESAW-192: Introduce a make command for pre-requisite of verify-replace script

.github/workflows/ci-build.yml
Updating the GolangciLint  to v1.63.1 across all repos and fixing the linter error if any from this upgrade
Similar PRs -
- Host-Operator - https://github.com/codeready-toolchain/host-operator/pull/1116
- Toolchain-Common - https://github.com/codeready-toolchain/toolchain-common/pull/442
- Member-Operator - https://github.com/codeready-toolchain/member-operator/pull/612
- Registration Service - https://github.com/codeready-toolchain/registration-service/pull/491
- Toolchain E2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/1092
- Ksctl - https://github.com/kubesaw/ksctl/pull/97
1. Did you run `make generate` target? **NA**
2. Did `make generate` change anything in other projects (host-operator, member-operator)? **NA** …
=> KUBESAW-250: Updating GolangCiLint  to v1.63.1

scripts/verify-replace.sh
This PR is to update the verify dependency script such a way that it prints the error/failure in an understandable way
1. Did you run `make generate` target? **NA**
2. Did `make generate` change anything in other projects (host-operator, member-operator)? **NA**
- Toolchain-common: …
=> KUBESAW-174: Print error output for repos where verification failed

api/v1alpha1/usersignup_types.go
Adds an annotation key that will keep the time of the signup request.
[SANDBOX-957](https://issues.redhat.com/browse/SANDBOX-957)
1. Did you run `make generate` target? **yes/no**
**NO** because adding annotation key doesn't require generating anything :smile:
=> add request-received-time annotation key

.github/workflows/ci-build.yml, .golangci.yml
upgraded `.golangci.yml` with `golangci-lint migrate`
=> chore(build): migrate to golangci-lint@v2 and golangci-lint-action@v7

make/generate.mk
I forgot to clean the envs when we dropped the fake GOPATH hack in #474, sorry!
3. In case of **new** CRD, did you the following? **yes/no**
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/# …
=> clean envs used in fake GOPATH hack
