README.md
=> Added simple building instructions until makefiles are ready

openshift-ci/Dockerfile.tools
=> chore: add Dockerfile to build on OpenShift CI

Makefile, make/go.mk
=> enable go modules in make goals

Makefile, make/go.mk
=> add goal to run tests in makefile

pkg/apis/toolchain/v1alpha1/useraccount_types.go, tools.go
to make the comparison/navigation easier
=> feat: introduce StatusUserAccount type

pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
=> fix: rename also Status.ResourceVersion to SyncIndex in MasterUserRecord

.github/pull_request_template.md
As desc here: https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository
To make sure when one change `api` project, he/she make sure to do corresponding changes in other projects.
Here is preview:
=> pr template added

go.mod, go.sum, pkg/apis/addtoscheme_kubefed_v1beta1.go
Register KubeFed types with the scheme
=> fix: register KubeFed types

pkg/apis/toolchain/v1alpha1/usersignup_types.go
This PR removes both the "PendingApproval" and "Provisioning" condition types from the UserSignup type, and adds the "Approved" condition type.
=> Modify condition types for UserSignup

.golangci.yml
=> add gofmt linter

pkg/apis/toolchain/v1alpha1/nstemplateset_types.go, pkg/apis/toolchain/v1alpha1/nstemplateset_types_test.go
second now pass by value
2. Does `make generate` change anything in other projects (host-operator, member-operator)? **[no]**
- host-operator: 
=> minor change - second now pass by value

pkg/apis/toolchain/v1alpha1/usersignup_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Fixes https://jira.coreos.com/browse/CRT-313
=> Removed UserID field from spec

scripts/olm-setup.sh
to make the olm scripts usable for toolchain-operator I had to:
* bring a new param option "operator-name" that will define the operator name
* when IMAGE var is set (when doing the release) then replase also the createdAt param
* change names of the hack resouces so it's not so long
**yes**
**yes**
- host-operator: https://github.com/codeready-toolchain/host-operator/pull113 …
=> feat: add operator-name param to CSV generation options & createdAt relpacement

pkg/apis/toolchain/v1alpha1/useraccount_types.go
Adding disabling reason
yes
no
=> Adding disabling reason

scripts/olm-setup.sh
It can maybe happen that the quay doesn't return digest when it's being requested via API call right after the image was pushed to the repository. To avoid having `null` as an image digest in CSV wait 10seconds for the digest being available or fail if the digest is not found within the timeout.
=> fix(CRT-472): wait until image digest is available or fail if is not found

pkg/apis/toolchain/v1alpha1/nstemplateset_types.go, pkg/apis/toolchain/v1alpha1/useraccount_types.go
Add tier label and reasons related to updates
yes
no but:
- member-operator: https://github.com/codeready-toolchain/member-operator/pull/129
=> chore: add ns update related label and reasons

pkg/apis/toolchain/v1alpha1/usersignup_types.go
moving usersignup reasons
yes
no
Relates to the following PR: https://github.com/codeready-toolchain/host-operator/pull/154
=> Usersignup reasons

pkg/apis/toolchain/v1alpha1/conditions.go, pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go, pkg/apis/toolchain/v1alpha1/nstemplateset_types.go, pkg/apis/toolchain/v1alpha1/useraccount_types.go
using consts to define re-used strings
yes
no
=> Reusing consts

scripts/olm-setup.sh
This PR adds support for both types of a directory that contains the operator bundle files - versioned and manifests.
The PR also fixes a small bug in a sed command that adds a correct replacement in the CSV
=> chore: support both versioned dir and manifests dir

pkg/apis/toolchain/v1alpha1/usersignup_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Adding annotations, labels and spec change for phone verification: 
Added constant for VerificationCode annotation name
Added constant for VerificationTimestamp annotation name
Added constant for VerificationCounter annotation name
Added constant for VerificationAttempts annotation name
Added constant for VerificationExpiry annotation name
Added constant for PhoneNumber label name
Added optional VerificationRequired boolean attribute to UserSignupSpec
Jira: https://issues.redhat.com/browse/CRT-759
Yes
Yes …
=> usersignup phone verification api changes

pkg/apis/toolchain/v1alpha1/banneduser_types.go
Adding banned user phone number label key constant
Jira: https://issues.redhat.com/browse/CRT-760
Yes
No
=> adding band user phone number label key

pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
adds `MemberToolchainClusterRemoved` reason constant - is used here: https://github.com/codeready-toolchain/host-operator/pull/275
=> chore: add MemberToolchainClusterRemoved reason condition

scripts/olm-setup.sh, scripts/push-bundle-and-index-image.sh
Adds params that let us specify index image URLs (new one as well as the previous one).
Used in this PR: https://github.com/codeready-toolchain/member-operator/pull/195
=> feat: introduce params to define index image url

pkg/apis/toolchain/v1alpha1/usersignup_types.go
Host operator: https://github.com/codeready-toolchain/host-operator/pull/307
=> Fix print column for usersignups

pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
Also see https://github.com/codeready-toolchain/host-operator/pull/314
=> Add MUR count print column to ToolchainStatus

make/generate.mk
add note that CRDs are listed in add-cluster.sh script https://github.com/codeready-toolchain/toolchain-common/pull/138#discussion_r518760908
=> chore: add note that CRDs are listed in add-cluster.sh script

scripts/olm-setup.sh
add support for a component image to CD scripts - this will be used in member-operator for releasing the operator together with a webhook image.
It just puts the webhook image into the CSV
=> feat: add support for component image to CD scripts

pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
Rename MemberToolchainClusterRemoved to MemberToolchainClusterMissing
Remove  unused `NoMemberClustersFound`
=> chore: rename MemberToolchainClusterRemoved to Missing

pkg/apis/toolchain/v1alpha1/usersignup_types.go, pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
A few sentences describing the overall goals of the pull request's commits.
2. Does `make generate` change anything in other projects (host-operator, member-operator, toolchain-common)? **yes** 
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/378
=> Make UserSignup.Spec.UserID required

scripts/push-bundle-and-index-image.sh
=> fix: use opm binary image 4.6

pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
=> feat: new constant for email addresses in MUR annotations

api/v1alpha1/toolchainstatus_types.go, api/v1alpha1/zz_generated.openapi.go
fixes https://issues.redhat.com/browse/CRT-1074
=> refactor: remove unused field in 'HostOperatorStatus'

scripts/olm-setup.sh
fix so the scripts run bundle makefile target in operator repo
=> fix: run bundle makefile target in operator repo

api/v1alpha1/masteruserrecord_types.go, api/v1alpha1/zz_generated.openapi.go
Fixes https://issues.redhat.com/browse/CRT-1321
See also:
https://github.com/codeready-toolchain/host-operator/pull/539
https://github.com/codeready-toolchain/toolchain-e2e/pull/411
https://github.com/codeready-toolchain/member-operator/pull/310
https://github.com/codeready-toolchain/registration-service/pull/227
=> refactor: new 'MasterUserRecord.Spec.TierName' field

api/v1alpha1/conditions.go, api/v1alpha1/nstemplateset_types.go, api/v1alpha1/space_types.go
=> feat: const for status when Space termination failed

api/v1alpha1/space_types.go
=> feat: const for status when Space provisioning failed

api/v1alpha1/zz_generated.openapi.go
adding missing generated YAML files :facepalm:
=> feat: Space.Status.TargetCluster field

api/v1alpha1/space_types.go
=> feat: add const for pending provisioning of spaces

.github/workflows/ci-build.yml, .golangci.yml, .yamllint, make/lint.mk
Run Go and YAML linters on GitHub Actions
=> chore: linter as a GitHub Action

.github/workflows/ci-build.yml
=> chore: update GolangCI linter action

.golangci.yml
=> chore: fix GolangCI config

api/v1alpha1/nstemplateset_types.go
See https://github.com/codeready-toolchain/member-operator/pull/327
=> feat: const for SpaceRoles provisioning failures

api/v1alpha1/conditions.go, api/v1alpha1/toolchaincluster_types.go
=> chore: update aliases

.github/workflows/ci-build.yml, .golangci.yml, api/v1alpha1/toolchainstatus_types.go, api/v1alpha1/zz_generated.openapi.go
=> refactor: rename Member.APIEndpoint field

.github/pull_request_template.md
PR template update. See discussion here: https://github.com/codeready-toolchain/host-operator/pull/632#discussion_r855185112
=> Update PR template to remind about updating POJECT and CSV

api/v1alpha1/socialevent_types.go
=> feat: add 'UnableToGetTier' reason for SocialEvents

api/v1alpha1/annotations.go, api/v1alpha1/usersignup_types.go
Refactors existing UserSignup annotations for SSO UserID and AccountID to make them generic.  No structural changes made so API regeneration is not required.
=> Introduced generic annotation keys for SSO UserID and AccountID

api/v1alpha1/useraccount_types.go
retrieve 'Tier' from label, include 'Created_at' and remove 'NS_Limit'
see also:
- https://github.com/codeready-toolchain/member-operator/pull/418
- https://github.com/codeready-toolchain/toolchain-e2e/pull/678
=> fix useraccount printcolumns

sonar-project.properties
https://issues.redhat.com/browse/SANDBOX-84
just updating the sonar properties file
=> fix: Update sonar properties

.github/workflows/ci-build.yml, go.mod
A few sentences describing the overall goals of the pull request's commits.
4. In case other projects are changed, please provides PR links. **N/A**
=> upgrade golang to 1.20

api/v1alpha1/usersignup_types.go
See https://github.com/codeready-toolchain/host-operator/pull/968
=> Fix usersignup email printcolumn

README.adoc
Just adding some more details to the readme. This is useful for further reference in the KubeSaw contribution guide.
=> add more details to the api doc

CODEOWNERS
=> project: add Rafaela, Feny, and Lukas to CODEOWNERS

.github/workflows/ci-build.yml, .github/workflows/verify-dependencies.yml
A few sentences describing the overall goals of the pull request's commits.
1. Did you run `make generate` target? **yes/no**
2. Did `make generate` change anything in other projects (host-operator, member-operator)? **yes/no**
3. In case of **new** CRD, did you the following? **yes/no**
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/# …
=> Switching GH runners to ubuntu-24.04

CODEOWNERS
JIRA: https://issues.redhat.com/browse/SANDBOX-1043
=> chore: Remove kanika from owners
